;(function () {
;(function () {
(function(){if(!window.b24form){window.b24form=function(e){b24form.forms=b24form.forms||[];b24form.forms.push(e);if(e.ref&&b24form.Loader&&!this.loaded){this.loaded=true;b24form.Loader.loadJs(e.ref,true)}}}if(window.b24form.Loader){return}function e(){this.requested=false;this.queue=[]}e.prototype={run:function(e){e=e||{};var o=e.resources||{};this.queue.push(e.form);if(!this.requested){var t=this.loadApp.bind(this,o.app);this.requested=true;if(o.polyfill&&!this.checkPolyfills()){this.loadJs(o.polyfill,true,t)}else{t()}}this.loadForms()},loadApp:function(e){if(!e){return}window.b24form.App?this.loadForms():this.loadJs(e,true,this.loadForms.bind(this))},loadForms:function(){if(!this.checkPolyfills()){return}if(!window.b24form.App){return}var e=this.queue;this.queue=[];e.forEach(this.loadForm,this)},loadForm:function(e){b24form.App.initFormScript24(e)},checkPolyfills:function(){return window.fetch&&window.Request&&window.Response&&window.Promise&&Object.assign&&Array.prototype.find&&Array.prototype.includes},loadJs:function(e,o,t){var i=document.createElement("SCRIPT");i.setAttribute("type","text/javascript");i.setAttribute("async","");if(o){i.setAttribute("src",e+"?"+(Date.now()/864e5|0));if(t){i.onload=t}this.appendToHead(i)}else{i.appendChild(document.createTextNode(e));this.appendToHead(i)}},appendToHead:function(e){(document.getElementsByTagName("head")[0]||document.documentElement).appendChild(e)}};window.b24form.Loader=new e})();
//# sourceMappingURL=https://haravan.bitrix24.vn/bitrix/js/crm/site/form/embed/unit/script.map.js

window.b24form.Loader.run({"form":{"id":"38","sec":"bmizc6","lang":"en","address":"https:\/\/haravan.bitrix24.vn","views":{"click":{"type":"panel","position":"right","vertical":"bottom"},"auto":{"type":"popup","position":"center","vertical":"bottom","delay":5}},"data":{"language":"en","design":{"style":"classic","border":{"bottom":true,"top":false,"left":false,"right":false},"color":{"primary":"#00aeef","primaryText":"#fff","text":"#000","background":"#ffffff","fieldBorder":"#00000012","fieldBackground":"#0000000d","fieldFocusBackground":"#fff"}},"title":"Li\u00ean h\u1ec7 t\u01b0 v\u1ea5n Gi\u1ea3i ph\u00e1p Haravan","desc":"Qu\u00fd kh\u00e1ch vui l\u00f2ng \u0111i\u1ec1n \u0111\u1ea7y \u0111\u1ee7 th\u00f4ng tin, Haravan s\u1ebd li\u00ean h\u1ec7 b\u1ea1n s\u1edbm nh\u1ea5t","buttonCaption":"\u0110\u0103ng K\u00fd T\u01b0 V\u1ea5n","useSign":false,"date":{"dateFormat":"DD\/MM\/YYYY","dateTimeFormat":"DD\/MM\/YYYY HH:MI:SS","sundayFirstly":false},"currency":{"code":"VND","title":"Vietnamese Dong","format":"# \u0026#8363;"},"fields":[{"id":"LEAD_TITLE","name":"LEAD_TITLE","label":"H\u1ecd v\u00e0 T\u00ean","visible":true,"required":true,"multiple":false,"type":"string","placeholder":null,"value":"","items":[],"hint":"","hintOnFocus":false,"autocomplete":false,"bigPic":false,"size":null,"contentTypes":null},{"id":"LEAD_PHONE","name":"LEAD_PHONE","label":"Phone","visible":true,"required":true,"multiple":false,"type":"phone","placeholder":null,"value":"","items":[],"hint":"","hintOnFocus":false,"autocomplete":false,"bigPic":false,"size":null,"contentTypes":null},{"id":"LEAD_EMAIL","name":"LEAD_EMAIL","label":"E-mail","visible":true,"required":true,"multiple":false,"type":"email","placeholder":null,"value":"","items":[],"hint":"","hintOnFocus":false,"autocomplete":false,"bigPic":false,"size":null,"contentTypes":null},{"id":"LEAD_UF_CRM_CD_TEXTBOX_1","name":"LEAD_UF_CRM_CD_TEXTBOX_1","label":"Chia s\u1ebb th\u00eam v\u1ec1 n\u1ed9i dung c\u1ea7n \u0111\u01b0\u1ee3c t\u01b0 v\u1ea5n","visible":true,"required":true,"multiple":false,"type":"string","placeholder":null,"value":"","items":[],"hint":"","hintOnFocus":false,"autocomplete":false,"bigPic":false,"size":null,"contentTypes":null}],"agreements":[],"dependencies":[],"recaptcha":{"use":false}}},"resources":{"app":"https:\/\/cdn.bitrix24.vn\/b28710635\/crm\/form\/app.js","polyfill":"https:\/\/cdn.bitrix24.vn\/b28710635\/crm\/form\/polyfill.js"}});
})();


})();